language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mvila@3base.com
  api_key:
    secure: TwB4mWioeRxSzye6nlS14EgLuN/DCEpmtM0NHVac7D5yanag1l3zsAplUwyW9hCi2Or1V/HaZvR8ypJALlIcF6GM+5pcH1z702sjyr0P3Wy8uNhUFw/vR+SnNBe3PNGSdqETeep3yNu3k0IqcszFWvpfBUJM5JNJdcYHsmudDMMBQsq1coxP4AJ69inkXQ+HuUt2Crp9Bcsv+kTzams6nKWH7rEO9MCyLRqTE4bBZ9rzWB+aPh85KzwSQ2O8ok8qxdiJI6S414WmK75ZtDhbg4XAqqgn5awCw/k2mjAbqImqR2quRWHsOlWazAY78rdDxEZvaNB2gVPvRHiXhdNiTRjlleVPdEAEyMfZI/c8P4KMUns4ejz06X+ET/vv0QNveFWQfAnUawH+RQnMsq9z1a3yKVg8HeKf5hmxkbAcdNquw3Tz58opyA9W2Ib+tVZrFOQgVG4A4xjlwlpaAxHXTtzupSN9FAW46AvsM9PrB4fKkJ4vRy6rCnbe65PcOJgxEpOdwJKdldApwI+pJZOP1RUOZyA1D2t6hWZRMFfA9DqenDTecQAlcijI/NE50a+NDJQB5P0gwZ/OYsxvQWZbJ4wG1skWYrls2Izn+dd+cyNr8JhcavHivlm+nN7f5JYnQpzF+CnaUmWgf0aYQoUFatcqK2/IZ2c20O65P0jlEoo=
  skip_cleanup: true
notifications:
  email: false
  slack:
    secure: jEiYY6i7twxmqLey2PWo71SLumrAR7NEjndrfmxP0WTrDnQfethSXjtp4zhyrzTqbcXozMpG/CkaZf1DZ6hS74H+8zGEXW3YdwIz+dsv89IYvM01JhQsjWOjp3LEjMkQj4VljHorTqSR4jEZYDff+ypKJvKi9MwSYcrQvLxRfLFADUL4ly9D+KPmfxfunIoyipUWIyxKjOSzQ0mZqiMV+U69C0WDu5anU/AsE5ba4T510O9+7D5bPzZhATwRI5GBaEHJFiNI4Dk8MFI6x59y/kQad0RsYU3rJOCdTin5md8UARjVDek7ZyMEovWCwZVm78wDo+H/UVFjCyiTgjbFgWdx/PfNyTysX8PMpF9PxGG668nyWj/EG18t8v/YEatE+Qheuuj/E3XNgwlCUBmFPFrc782nnGSV3InGXS7J5EXwnejQaSErQf9EN7lKG5Q8xNpWB+Nb30A14mmKOeZYvptaQ11dMbp/1fA0Nt7675Qp2uf6UQfg+VolFT/4rGLNDadWy9gCfC9lR/BwBmCbYFDcjxKTjB7yeEKB7TPrz14AHeYVvtLVFBqx6iDOTuVyxr8xOH1MzHIbj4uU2XJTkPq+x8bW2Hvls5PgL6dutgYiwz+jZj34fepVM6I5GQSuaakiSiRetzD9Aq+S4mh4QF7l1/uuHLyjq6srzm1X1zY=
sudo: false
