language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mvila@3base.com
  api_key:
    secure: Un/KXDRGg1CxRjFBpuFPwnrTOJawQaQrGwxxAPRKDcpDxb6lA+2do38kz5eBDnORdca1pX2wEChzeWsKIMa0mvVHBeOVnvMok+h8mYaQKN6f1GznuaBmZ5AkDbcXFHHrTli13uq7A0h6tY2WAIPU+voS30wTWvUCXKtaFXQ5R5Doy9NmqQCWYi5BtcEn60ILjVuh2NCSgXKYlUsgLQOlkPsfLUtVndwHT9nQ6nB2VTjF46PAipT7SvE+p15mDWWXFdJ0yF/Fy94EEV48orR8fykcym2pv/iDgJ1ETt/s1Kk4AipIhJ1I7kFy8x8EzeTwUFEchtFbHJibHgrLYxMb7euf5SBqCjCajPGtViYe9akDXJqFch9QxA7hSpBy6On+8kKnVWjIdWouST5sSSxSG4CF7b+K3o8CPuZfMjlA2xG+usabzV2l8wD9JDLUZNToiHajBTIK3le77jRWVOMsk431TuEZXrgMZtawvoJ5/gOCoDnQAkI1veT66WoV+OKHPmg7xACQKQh8BqW7/aprbfNZEZtwTn/rqiEgJhTyEGCKZzFFo7MfyG+ZOZr7YFV5LlaJnODHyUpG+aR64CfCz+Rzi4gb9ZWy1IqvQPM1hC0hw2I7YfooSPyyF7KDwXqEkELLc2ymFjzzpYrSER28tmcwZ1JFY3S8V3WUnNrmgG0=
  skip_cleanup: true
notifications:
  email: false
  slack:
    secure: IsGDzJWjRUiz55G+bKvFGRgxM2j1icqxNX9eUXbbKP6bWgGNQfiLsmBgzZEOKmLosPj0SzpBLDNY9zwuD4r0XMhxmTutRobiEbnLvG6+yCluU5PW/AOerHyjiMgXvyWr8djV3bRvJok+lIAjU4RX2W04PT2jXViJ/8Hsx+e6jNCtvRHhbaGppngXq9pJoSTH/KHrR3AMEkJlGJ7FtyANkxAchetQ3xeMMwaXRpNmC9qDUfI0MCrE2cGukyftqXeOXQwSB9PDqBai7ddTKlM6fF1XBJBfN7NhL3pN2RJwcg9OHn1fSmlQPJwM4LX4dibEoes3QVXYHiVjzbDLLs9HUUUbx4Y2yFXEPoqVw35QR46OlVjaMmEFhQo81/3mAwaQCHDmNZstReuDYFaaD4yU2glow8wWCoKsxzg3Ip2lBp6jdfzgAyG3OwfVOgD0A7hpBFQHwAAkfJHEduG8HeFb9VPUDD2MMEZ58oCzvfsM68+ihMmALqXvjW7DI1G7v2DAPswv4Jp0trWjVWAweeV7/3V24rrwfuyfL3BxYP/hqF9svXVmRSB0v8lPrXZuinVL6cHqeRc4jn3q9M8nBsMzJ/zLhIJt4r8w2oUkwvpNpuWmcvnHPRE34rhgk0KhzdUf1GnWOKkSRrWAjxQCZagZjQod00Lod418K8CQzXLrU7Y=
sudo: false
